apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: redmine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: REDMINE_DB_POSTGRES
              value: {{ .Values.database.host | quote }}
            - name: REDMINE_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: dbname
            - name: REDMINE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: username
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: password
            - name: REDMINE_SITENAME
              value: {{ .Values.redmine.siteName | quote }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
