apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redmine
  namespace: staging
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/redmine
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    redmine:
      siteName: "Redmine Staging"
    replicaCount: 1
    ingress:
      enabled: true
      className: traefik
      host: redmine.staging.local
      tls:
        enabled: true
        secretName: redmine-tls
    database:
      host: redmine-db-rw
      existingSecret: redmine-db-app
    resources: {}
    hpa:
      enabled: false
